/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3EAPPSFLYER_AUTODEFS_H
#define S3EAPPSFLYER_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_APPSFLYER_NAME "s3eAppsFlyer"
#define S3E_EXT_APPSFLYER_HASH 0xc0bbea26

#endif /* !S3EAPPSFLYER_AUTODEFS_H */
